repository:
  protected_branches:
    - name: main
      required_pull_request_reviews:
        require_code_owner_reviews: true
        required_approving_review_count: 1
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: true
      restrictions: null
  delete_branch_on_merge: true
  allow_merge_commit: false
  allow_squash_merge: true
  allow_rebase_merge: false
  default_branch: main
